export enum toolsEnum {
    vite = 'vite',
    typescript = 'typescript',
    react = 'react',
    react_router = 'react-router',
    redux = 'redux',
    react_hook_form = 'react-hook-form',
    scss = 'scss',
    framer_motion = 'framer-motion',
    css = 'css',
    html = 'html',
    figma = 'figma',
    adobe_photoshop = 'adobe-photoshop',
    skeleton = 'skeleton',
}
